### ISSUE TITLE
I'm getting this error, can someone help me?

### ISSUE THREAD

**Issue by ZeSpama** [Summer-16/CSGO-VMPanel#54]
10ac74c4468cb5f8da55e81921e69556] [2022-09-05T04:53:56.643] [ERROR] <User Model> {models/userModel.js:82} => error in createTheTableIfNotExists-> Error: connect ETIMEDOUT
    at PromisePool.query (/home/zespama/CSGO-VMP/Panel_Server/node_modules/mysql2/promise.js:341:22)
    at Object.query (/home/zespama/CSGO-VMP/Panel_Server/app/db/db_bridge.js:32:34)
    at /home/zespama/CSGO-VMP/Panel_Server/app/models/userModel.js:48:33
    at new Promise (<anonymous>)
    at Object.createTheTableIfNotExists (/home/zespama/CSGO-VMP/Panel_Server/app/models/userModel.js:37:12)
    at bootstrap (/home/zespama/CSGO-VMP/Panel_Server/app/db/bootstrap.js:33:21)
    at Object.<anonymous> (/home/zespama/CSGO-VMP/Panel_Server/server.js:126:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
[c38d0d3d81b597479430fb55c246d164] [2022-09-05T04:53:56.646] [ERROR] <Server> {Panel_Server/server.js:133} => Error while doing database bootstrapping Error: Error: connect ETIMEDOUT
    at PromisePool.query (/home/zespama/CSGO-VMP/Panel_Server/node_modules/mysql2/promise.js:341:22)
    at Object.query (/home/zespama/CSGO-VMP/Panel_Server/app/db/db_bridge.js:32:34)
    at /home/zespama/CSGO-VMP/Panel_Server/app/models/userModel.js:48:33
    at new Promise (<anonymous>)
    at Object.createTheTableIfNotExists (/home/zespama/CSGO-VMP/Panel_Server/app/models/userModel.js:37:12)
    at bootstrap (/home/zespama/CSGO-VMP/Panel_Server/app/db/bootstrap.js:33:21)
    at Object.<anonymous> (/home/zespama/CSGO-VMP/Panel_Server/server.js:126:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}

**Comment by shaikhnedab** [comment]
is your database server up and running?
does it allow remote connction?
